# Generated by Django 6.0.7 on 2026-08-01 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='full_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2005, 6, 8)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='language_preference',
            field=models.CharField(default=datetime.date(2005, 6, 8), max_length=50),
            preserve_default=False,
        ),
    ]
