# Generated by Django 5.2.17 on 2026-08-23 07:02

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0004_medicaldocument_error_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('relationship', models.CharField(choices=[('family', 'Family Member / Spouse'), ('child', 'Son / Daughter'), ('parent', 'Parent'), ('nurse', 'Nurse / Attendant'), ('friend', 'Friend / Neighbor'), ('other', 'Other Caregiver')], default='family', max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notify_on_missed', models.BooleanField(default=True, help_text='Send alert if medication is missed for 2+ hours')),
                ('notify_on_emergency', models.BooleanField(default=True, help_text='Notify immediately during Emergency SOS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregivers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(blank=True, help_text='e.g. 500mg, 1 tablet', max_length=100, null=True)),
                ('frequency', models.CharField(default='1-0-1', help_text='e.g. 1-0-1, OD, BD, TDS', max_length=100)),
                ('is_morning', models.BooleanField(default=True)),
                ('morning_time', models.TimeField(default=datetime.time(8, 0))),
                ('is_afternoon', models.BooleanField(default=False)),
                ('afternoon_time', models.TimeField(default=datetime.time(13, 0))),
                ('is_night', models.BooleanField(default=True)),
                ('night_time', models.TimeField(default=datetime.time(20, 0))),
                ('food_timing', models.CharField(choices=[('before_meal', 'Before Food'), ('after_meal', 'After Food'), ('with_meal', 'With Food'), ('anytime', 'Anytime / As Directed')], default='after_meal', max_length=50)),
                ('duration_days', models.IntegerField(default=5, help_text='Duration in days')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, help_text='e.g. Antibiotic, Pain Relief', max_length=100, null=True)),
                ('usage_summary', models.TextField(blank=True, help_text='Clinical usage / indication', null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='documents.medicaldocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('slot', models.CharField(choices=[('morning', 'Morning (8:00 AM)'), ('afternoon', 'Afternoon (1:00 PM)'), ('night', 'Night (8:00 PM)')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('taken', 'Taken'), ('missed', 'Missed'), ('skipped', 'Skipped / Snoozed')], default='pending', max_length=20)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_logs', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='reminders.medicationschedule')),
            ],
            options={
                'unique_together': {('schedule', 'date', 'slot')},
            },
        ),
    ]
