# Generated by Django 6.1 on 2026-08-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationlog',
            name='missed_alert_sent',
            field=models.BooleanField(default=False, help_text='Prevents duplicate caregiver SMS alerts'),
        ),
        migrations.AddField(
            model_name='medicationlog',
            name='missed_alert_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
