# Generated by Django 5.2.17 on 2026-08-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthEducationArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('preventive', 'Preventive Healthcare'), ('maternal', 'Maternal Health'), ('child_care', 'Child Healthcare'), ('elderly_care', 'Elderly Care')], db_index=True, max_length=50)),
                ('icon', models.CharField(default='FaHeartbeat', max_length=50)),
                ('read_time_minutes', models.IntegerField(default=3)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('key_takeaways', models.JSONField(default=list)),
                ('title_te', models.CharField(blank=True, max_length=255)),
                ('summary_te', models.TextField(blank=True)),
                ('content_te', models.TextField(blank=True)),
                ('key_takeaways_te', models.JSONField(blank=True, default=list)),
                ('title_hi', models.CharField(blank=True, max_length=255)),
                ('summary_hi', models.TextField(blank=True)),
                ('content_hi', models.TextField(blank=True)),
                ('key_takeaways_hi', models.JSONField(blank=True, default=list)),
                ('title_mr', models.CharField(blank=True, max_length=255)),
                ('summary_mr', models.TextField(blank=True)),
                ('content_mr', models.TextField(blank=True)),
                ('key_takeaways_mr', models.JSONField(blank=True, default=list)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
