# Generated by Django 5.2.16 on 2026-08-06 09:51

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealthcareContent',
        ),
        migrations.RemoveField(
            model_name='medicaldocument',
            name='extracted_text',
        ),
        migrations.RemoveField(
            model_name='medicaldocument',
            name='original_language',
        ),
        migrations.RemoveField(
            model_name='medicaldocument',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='medicaldocument',
            name='title',
        ),
        migrations.RemoveField(
            model_name='medicaldocument',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='document_name',
            field=models.CharField(default='Untitled', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('translated', 'Translated'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='document_type',
            field=models.CharField(choices=[('image', 'Image')], default='image', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='file',
            field=models.FileField(upload_to='medical_documents/%Y/%m/', validators=[documents.models.validate_image_file]),
        ),
        migrations.DeleteModel(
            name='PatientHistory',
        ),
    ]
