# Generated by Django 5.2.16 on 2026-08-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_delete_healthcarecontent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocument',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
    ]
