# Generated by Django 5.2.16 on 2026-08-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_medicaldocument_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocument',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
