# Generated by Django on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_medicaldocument_extracted_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='MedicalDocument',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
