# Generated by Django 5.2.17 on 2026-08-23 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(choices=[('hospital', 'Hospital & Trauma Center'), ('emergency_room', '24/7 Emergency Room'), ('pharmacy', '24/7 Pharmacy'), ('blood_bank', 'Blood Bank'), ('cardiac_center', 'Cardiac Emergency Center'), ('burn_unit', 'Burn Center')], default='hospital', max_length=50)),
                ('address', models.TextField()),
                ('city', models.CharField(default='Hyderabad', max_length=100)),
                ('state', models.CharField(default='Telangana', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(max_length=30)),
                ('emergency_hotline', models.CharField(blank=True, max_length=30, null=True)),
                ('ambulance_phone', models.CharField(default='108', max_length=30)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_24_hours', models.BooleanField(default=True)),
                ('has_icu', models.BooleanField(default=True)),
                ('has_blood_bank', models.BooleanField(default=True)),
                ('available_services', models.TextField(blank=True, help_text='e.g. Trauma Care, Cardiac ICU, CT Scan', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('relationship', models.CharField(help_text='e.g. Spouse, Brother, Doctor, Neighbor', max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
