# Generated by Django 5.2.17 on 2026-08-27 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyHealthTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('nutrition', 'Diet & Nutrition'), ('hydration', 'Hydration & Water Safety'), ('hypertension', 'Blood Pressure Management'), ('diabetes', 'Sugar Management'), ('general', 'Daily Vitality')], default='general', max_length=50)),
                ('tip_text', models.CharField(max_length=500)),
                ('tip_text_te', models.CharField(blank=True, max_length=500)),
                ('tip_text_hi', models.CharField(blank=True, max_length=500)),
                ('tip_text_mr', models.CharField(blank=True, max_length=500)),
                ('author_badge', models.CharField(default='Clinical AI Sahayak', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('doctor_visit', 'Doctor Consultation Follow-Up'), ('lab_retest', 'Diagnostic Lab Re-Test'), ('vitals_check', 'Vitals & BP Monitoring'), ('medication_review', 'Medication Refill & Review')], default='doctor_visit', max_length=50)),
                ('reason', models.TextField()),
                ('recommended_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
